data:
  num_images: 1000
  batch_size: 1
model:
  name: inceptionv3
  train_config:
    learning_rate: 0.0001
    train_steps: []
attack:
  method: FGSRA
  steps: 10
  eps: 16
  rho: 0.5
  beta: 3.5
  max_iter: 20
  save_steps:
    - 9
